### ISSUE TITLE
Ignore certain error types 

### ISSUE THREAD

**Issue by martin-rog001** [appoptics/appoptics-apm-node#65] opened 2019-04-30 16:20 UTC
Further to my conversation with AppOptics support staff, we were discussing potential options to disable certain errors from being recorded by the agent.

I'm currently having an issue where my exception logs are full of thousands of these exceptions:
```
ENOENT: no such file or directory, stat 
```

They aren't of any use to us, so it would be great to have an option to filter these out of the dashboard (https://my.appoptics.com/apm/ - > Exceptions). Or more effectively, tell the agent to ignore these before pushing up to AppOptiocs.

Many thanks

Martin

**Comment by bmacnaughton** [comment] 2019-10-28 15:18
Martin, thanks for this request. It's implemented in v6.9.0. Please let me know how it works for you.

Take a look at the [guide](https://github.com/appoptics/appoptics-apm-node/blob/master/guides/configuration.md) for some more information but the general idea is:

```
{
  "enabled": true,
  "serviceKey": "...",
  "probes": {
    "fs": {
      "enabled": false,
      "ignoreErrors": {
        "open": {
          "ENOENT": true
        }
      }
    }
  }
}
```

**Comment by bmacnaughton** [comment] 2019-11-20 12:41
Closing as the feature has been added.

**Comment by immohitrathi** [comment] 2021-01-15 13:36
I want to ignore below such errors in appoptics which are showing as exceptions for each request, this is non breaking and page works just fine. 

ENOENT: no such file or directory, stat '/opt/node_app/app/public/healthcheck'
ENOENT: no such file or directory, stat '/opt/node_app/app/public/akansha-deep-heights-kunhari-kota-npxid-r353279'
ENOENT: no such file or directory, stat '/opt/node_app/app/public/reviews/project-and-locality-reviews'

As per above comment, should I keep this as it is or I need to pass `enabled` as `true` for `fs` probe in below json config??  I don't want to ignore other `fs` exceptions.

{
  "enabled": true,
  "serviceKey": "...",
  "probes": {
    "fs": {
      "enabled": false,
      "ignoreErrors": {
        "open": {
          "ENOENT": true
        }
      }
    }
  }
}

**Comment by bmacnaughton** [comment] 2021-01-15 15:08
if `fs` is set `"enabled": false` then no `fs` events will be reported. that will suppress errors but it will also suppress all `fs` events.

i think you want `"enabled": true` if i understand correctly.

**Comment by immohitrathi** [comment] 2021-01-19 08:54
@bmacnaughton  
I would like to thank you for being so helpful with issues being faced. 

I have put below `appoptics-apm-config.json` file at the project root directory but I can still see these ENOENT exceptions on appoptics dashboard. Is there anything I'm missing here? 

Sample exceptions:
ENOENT: no such file or directory, stat '/opt/node_app/app/public/healthcheck'
ENOENT: no such file or directory, stat '/opt/node_app/app/public/reviews/project-and-locality-reviews'

`{
  "enabled": true,
  "serviceKey": "YAE*************************************:content-99webreact-prod",
  "probes": {
    "fs": {
      "enabled": true,
      "ignoreErrors": {
        "open": {
          "ENOENT": true
        }
      }
    }
  }
}`

**Comment by bmacnaughton** [comment] 2021-01-19 12:28
without more information i can't be sure, but it looks like you're executing a `stat` call. you will need to add `"stat": {"ENOENT": true}` to the `ignoreErrors` object.

**Comment by immohitrathi** [comment] 2021-01-19 12:41
is this what you meant?

{
  "enabled": true,
  "serviceKey": "YAE********************************************:content-99webreact-prod",
  "probes": {
    "fs": {
      "enabled": true,
      "ignoreErrors": {
        "open": {
          "ENOENT": true
        },
        "stat": {
          "ENOENT": true
        }
      }
    }
  }
}

**Comment by bmacnaughton** [comment] 2021-01-19 13:28
yes, sorry for the delay.

**Comment by immohitrathi** [comment] 2021-01-20 04:30
@bmacnaughton  this is still not working as suggested by you above, I have attached few dashboard SS for your reference. Please let me know the details needed to debug this. These spans are internally triggered from appoptics for each request. Thanks

![image](https://user-images.githubusercontent.com/17422582/105126953-d3203700-5b05-11eb-8a34-911835c32862.png)
![image](https://user-images.githubusercontent.com/17422582/105127015-f2b75f80-5b05-11eb-8011-41d82671d9b4.png)

**Comment by bmacnaughton** [comment] 2021-01-20 11:23
i will take a look at this later this week. in the meantime disabling `fs` should work.

is your code performing an `fs.statSync` or an `fs.stat`? if this is the result of an `fs.statSync` call then setting the option `throwIfNoEntry` to `false` *might* solve the problem.

**Comment by immohitrathi** [comment] 2021-01-20 12:11
I am not using these functions in my code, not sure if some internal/external library(morgan, winston etc) is using or not.

**Comment by bmacnaughton** [comment] 2021-01-20 12:25
is there a stack trace if you dig into the spans?

**Comment by immohitrathi** [comment] 2021-01-20 12:37
This is what is there in the trace on dashboard


at Object.backtrace (/opt/node_app/app/node_modules/appoptics-apm/lib/api.js:286:15)
at runSpan (/opt/node_app/app/node_modules/appoptics-apm/lib/api.js:911:42)
at runInstrument (/opt/node_app/app/node_modules/appoptics-apm/lib/api.js:898:10)
at Object.instrument (/opt/node_app/app/node_modules/appoptics-apm/lib/api.js:789:10)
at Object.f [as stat] (/opt/node_app/app/node_modules/appoptics-apm/lib/probes/fs.js:126:19)
at SendStream.sendFile (/opt/node_app/app/node_modules/send/index.js:721:6)
at SendStream.pipe (/opt/node_app/app/node_modules/send/index.js:595:8)
at serveStatic (/opt/node_app/app/node_modules/serve-static/index.js:125:12)
at Layer.handle [as handle_request] (/opt/node_app/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/opt/node_app/app/node_modules/express/lib/router/index.js:317:13)

**Comment by bmacnaughton** [comment] 2021-01-20 12:46
thanks for your help. i will take a look at this as i mentioned; i'm working on an issue i need to complete but should get to this later this week or on the weekend.

**Comment by bmacnaughton** [comment] 2021-01-23 15:00
the problem is in `lib/probes/fs.js` code, line 179: `if (method === 'open')`. it was a mistake to make the code specific to 'open'. if you're open to patching just replace the test with `if (true)` or remove the entire conditional.

otherwise i'll let you know when i can get a release out with this code.

**Comment by immohitrathi** [comment] 2021-01-23 15:24
@bmacnaughton thank you for taking time out to look into this on a weekend. We cache the node modules and patching can be tricky in the kubernetes environment. So I would request if you can fix it in next release.

thanks

**Comment by immohitrathi** [comment] 2021-01-28 05:30
@bmacnaughton  please tell when will the fix be released? We're holding on the migration to 100% due to this. I can see your changes being merged in master. Thanks.

**Comment by bmacnaughton** [comment] 2021-01-28 12:13
there will be a new major release before the end of next week that contains this fix as well as others. it will use node-pre-gyp so for even numbered LTS releases you will not need to have the build chain (gcc, python2, etc.) to deploy the software.

**Comment by bmacnaughton** [comment] 2021-01-30 15:49
@immohitrathi this is addressed in v10.0.0-rc1 which is now available on npm.

as there are quite a few changes in this release it would be great if you get a chance to give it a try. one of the biggest changes is that it does not require having the gcc toolchain installed if you're using one of the node LTS (even numbered) versions (the prebuilt binaries are tied to the node [node module version (aka ABI)](https://nodejs.org/en/download/releases/)).

i am closing this again. let me know know if you have any problems with it. if there are other issues with 10.0.0-rc1 open a new issue.

**Closed by bmacnaughton** 2021-01-30 15:49 UTC
Labels: enhancement

**Comment by bmacnaughton** [comment] 2021-02-01 19:07
@immohitrathi - can you verify that you've tried v10.0.0-rc1? i'd like to have your postive confirmation before i release it for general availability.

**Comment by immohitrathi** [comment] 2021-02-02 01:39
@bmacnaughton  I have tried this and everything looks good, also the exceptions are no more there. Thanks

**Comment by bmacnaughton** [comment] 2021-02-02 11:28
thanks you for your help. i will leave this closed. keep your eye out for a general release.
